### PR TITLE
Add spawnrate config (global) and command (current map)

### PR DESCRIPTION
**Pull request by peamy**
Hey, I made this because I felt the need to increase the mob spawns.
The spawnrate can be configured in config.yml.

I also made the `@spawnrate` command, which increases the spawnrate of the current map.

```
GLOBAL_MAX_MOBS_PER_SPAWNPOINT: 2   # Maximum amount of (live) mobs one spawnpoint can have    
GLOBAL_MOB_SPAWN_RATE: 2  # How many more mobs the map should spawn (capped by GLOBAL_MAX_MOBS_PER_SPAWNPOINT) 
```

I've checked the config in with both values on 2. But if you want the normal behavior, you should set both to 1.

Normal spawns:
```
GLOBAL_MAX_MOBS_PER_SPAWNPOINT: 1
GLOBAL_MOB_SPAWN_RATE: 1
```

For any questions, don't hesitate to ask me.

### CODE REVIEW

**Comment by P0nk** [comment]
Hi, while this is a cool feature it doesn't really align with the goal of Cosmic, which is to be vanilla v83. The respawn system isn't vanilla to begin with and I'd like to avoid doubling down on it.

**Comment by BioRage** [comment]
@peamy 

Is there a way from prevent bosses to double down on it? I do like this feature overall, but bossess tend to spawn immediately after killing them, or in some cases, twice.

**Comment by BioRage** [comment]
Also, @peamy This causes issues with instance based maps.

Example:

Kerning Square:

!warp 103040400
!startquest 2286

having this quest and talking first line "I'm helping...", should warp you to RockSpirt.js event, (instance) but doesn't. After removing the code, it works again. Something to do with how instances are handled. 

NPC is 1052125.js

**Comment by P0nk** [comment]
> Also, @peamy This causes issues with instance based maps.
> 
> Example:
> 
> Kerning Square:
> 
> !warp 103040400 !startquest 2286
> 
> having this quest and talking first line "I'm helping...", should warp you to RockSpirt.js event, (instance) but doesn't. After removing the code, it works again. Something to do with how instances are handled.
> 
> NPC is 1052125.js

That is because peamy removed two methods in MapleMap for some reason. `instanceMapRespawn()` and `instanceMapForceRespawn()`

**Comment by TamereGH** [comment]
Well, the spawn rate works well, but all the mobs of my game have stopped moving. 
Even if i delete all your code. 

Any solution?

**Pull request closed without merging**
