### PR TITLE
Fix Mai's Last Training

### PR DESCRIPTION
**Pull request by anliting**
The mission target is pig, but only orange mushrooms are in the map:
image

Change orange mushrooms into pigs.

### CODE REVIEW

**Comment by anliting** [comment]
I see.

I am thinking why I am seeing this dialog, the text doesn't seem to be appearing in the source:
image

Any hint about how may I solve this issue?

**Comment by P0nk** [comment]
Look up the NPC id of Mai in the handbook, find the script file (<id>.js) and look through the JavaScript code.

**Comment by anliting** [comment]
The NPC ID of Mai is 12100. However, there is no `scripts/npc/12100.js`.

The quest ID of Mai's Last Trianing is 1044. However, there is no `scripts/npc/1044.js`.

I have not found the map with pigs, which you have mentioned, in wz/Map.wz/Map/Map0.

The portal script is [scripts/portal/entertraining.js](https://github.com/P0nk/Cosmic/blob/master/scripts/portal/entertraining.js). I only searched in wz/Map.wz/Map/Map0, because referencing scripts/portal/entertraining.js, if there is such a map, it is very likely it is in wz/Map.wz/Map/Map0.

I speculate that the quest description is loaded from the WZ files in the client. The client I am using is almost the offical one, only dinput8.dll and MapleStory.exe is replaced.

Did I choose the wrong client? Maybe somewhere states the server should be using with some edited WZ files but I carelessly ignored that statement.

Could you please give me the ID of the map you have mentioned above?

**Comment by anliting** [comment]
Oops, I see that statement now...

Sorry for disturbing and thank for your patience.

**Comment by P0nk** [comment]
My bad, of course it's a portal script.

**Comment by anliting** [comment]
After applying the CosmicWZ-v1-2021.05.10.zip, there is no inconsitency anymore:
image

**Pull request closed without merging**
